### ISSUE TITLE
Add company name to report

### ISSUE THREAD

**Issue by jlandells** [coltoneshaw/mmhealth#11]
**Describe the solution you'd like**
The current report is titled "Mattermost Healthcheck Report".  My enhancement request is to have a command line flag to pass an optional company name which, if present, gets added to the report title, such as "Mattermost Healthcheck Report for Acme Inc."

![image](https://github.com/coltoneshaw/mmhealth/assets/12452325/95814a13-f134-475c-b20b-e96db944d9bd)

**Describe alternatives you've considered**
There are two workarounds if we opt not to implement this:

1. Include a CLI parameter that pauses at the markdown output, to allow the file to be updated by hand (which might be valuable for other reasons)
2. The output PDF can be edited manually (with the appropriate tools) to add the company name by hand, as shown in the example below:
![image](https://github.com/coltoneshaw/mmhealth/assets/12452325/4ad70beb-cbb9-4a08-afce-063c53d66c1b)

**Comment by coltoneshaw** [comment]
Since the packet contains a `licensedTo` I've included it at the top by default, like this.

![Screenshot 2024-03-18 at 10 45 06 PM](https://github.com/coltoneshaw/mmhealth/assets/46071821/65d1bb51-6da9-4a28-a772-beb3e7eaa755)

Also it can be overridden with `-c` / `--company`
