### ISSUE TITLE
Update font to a Sans Serif version

### ISSUE THREAD

**Issue by jlandells** [coltoneshaw/mmhealth#12]
**Is your feature request related to a problem? Please describe.**
The Mattermost Brand Guidelines state that the primary font should be [Trade Gothic Next](https://fonts.adobe.com/fonts/trade-gothic-next), which is a sans-serif typeface.  The report is currently produced using a more ornate serif font.

**Describe the solution you'd like**
Ideally, the report would be generated with the official font (see example screenshot below), but if this is not available, the Brand Guidelines recommend Roboto as a good alternative.  Any sans-serif font would look closer to the brand than the default font currently in use.

![image](https://github.com/coltoneshaw/mmhealth/assets/12452325/61880ab4-d228-48d0-b5b6-111d22b3d489)

**Comment by jlandells** [comment]
From my research, it looks like these 2 lines near the top of the Latex template should do the trick:

``` latex
\usepackage[stfdefault]{roboto}
\usepackage[T1]{fontenc}
```

**Comment by coltoneshaw** [comment]
![Screenshot 2024-03-19 at 8 31 17 AM](https://github.com/coltoneshaw/mmhealth/assets/46071821/06a0442d-e7b0-4bbb-8d00-e7585fb48172)


This is currently how it looks, thoughts?
