### ISSUE TITLE
v0.5.0 not producing a complete report!

### ISSUE THREAD

**Issue by jlandells** [coltoneshaw/mmhealth#17]
**Describe the bug**
Since upgrading to v0.5.0 of `mmhealth`, the font looks great, but there are a couple of fundamental issues:

- The company name is missing from the header (not the biggest issue)
- The log and plugin sections have no data in the tables

Output from `mmhealth`:
```
Processing file:  mattermost_support_packet_2024-03-06-02-21/
Processing file:  mattermost_support_packet_2024-03-06-02-21/cpu.prof
Processing file:  mattermost_support_packet_2024-03-06-02-21/goroutines
Processing file:  mattermost_support_packet_2024-03-06-02-21/heap.prof
Processing file:  mattermost_support_packet_2024-03-06-02-21/mattermost.log
Processing file:  mattermost_support_packet_2024-03-06-02-21/notifications.log
Processing file:  mattermost_support_packet_2024-03-06-02-21/plugins.json
Processing file:  mattermost_support_packet_2024-03-06-02-21/sanitized_config.json
Processing file:  mattermost_support_packet_2024-03-06-02-21/support_packet.yaml
Error parsing version for plugin com.<redacted>: Invalid Semantic Version
Error parsing version for plugin com.<redacted>: Invalid Semantic Version
Error parsing version for plugin support-bot-plugin: Invalid Semantic Version
PDF generated successfully.
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Run a healthcheck against a valid support packet
2. Check the PDF
3. Notice missing data

**Expected behaviour**
The report was populated with the correct data in the previous version.  There must be an error somewhere that's not being reported.

**Screenshots**
![image](https://github.com/coltoneshaw/mmhealth/assets/12452325/d4d21f33-bdf4-4b2f-b81a-417cce80b92d)
![image](https://github.com/coltoneshaw/mmhealth/assets/12452325/427443a6-0356-4928-8418-a0a78afc64e3)
![image](https://github.com/coltoneshaw/mmhealth/assets/12452325/788002ed-3e14-45d7-b686-428ee575fb82)

**Desktop (please complete the following information):**

- OS: macOS Sonoma (v14.3.1)
- Docker Desktop: v4.28.0
- Docker Image ID: 04e5e0f273d4c49a57594d2e06bd0c55935dfd4cbec77bb772e99ff31c5ff8d0 (tagged as `latest`)
- MD5 of `mmhealth`: 3f223b86184683668d674c85205248b8

**Comment by coltoneshaw** [comment]
Solved via DM.
