### ISSUE TITLE
Check for bad post count

### ISSUE THREAD

**Issue by jlandells** [coltoneshaw/mmhealth#5]
**Describe the bug**
In `environment.go`, there's a check to see whether Elasticsearch is recommended, based on the `total_posts` value from the support packet.  In the case where an invalid value is embedded in the support packet (`-1` in my case), the report simply counts that as `<2500000`, which may not be correct.

**To Reproduce**
Steps to reproduce the behaviour:

1. Modify the `support_packet.yaml` file to set `total_posts: -1`
2. Run the health check.

**Expected behaviour**
When an invalid value is returned in the support packet, it would be better to highlight this, rather than giving the impression that everything is fine.

**Comment by coltoneshaw** [comment]
Good catch! Let me fix that.

**Comment by coltoneshaw** [comment]
My thinking here is for some of these we check `MaxUsersForStatistics` against active users, and show a specific error if a value is needed but not found. 

Just trying to think how to make it easily repeatable without overly complicating it. My thought is to add an `error` result to all healthchecks to if the check fails, we just log the error message.

**Comment by jlandells** [comment]
I think it's worth keeping the check simple.  If it's <0, simply include a message saying something like "Total post count unavailable.  Please validate manually."

**Comment by coltoneshaw** [comment]
Shows an error in the cli now:

```
Processing file:  support_packet.yaml
Processing file:  notifications.log
Processing file:  mattermost.log
Processing file:  sanitized_config.json
Processing file:  plugins.json
2024/03/12 14:20:58 Failed to get total posts for check h009. Usually because MaxUsersForStatistics is set lower than the actual number of users.


PDF generated successfully.

```

And shows an error on the report

![Screenshot 2024-03-12 at 2 38 23 PM](https://github.com/coltoneshaw/mmhealth/assets/46071821/620aebb0-82a4-4fbb-8166-9175089ded00)
