### ISSUE TITLE
IDs would scan better if upper case

### ISSUE THREAD

**Issue by jlandells** [coltoneshaw/mmhealth#6]
**Describe the bug**
The health check report displays IDs in lowercase.  This doesn't scan well and is in contrast to how the IDs are displayed in the summary document.

**Expected behaviour**
It would look better (and be more consistent) if the ID fields were converted to uppercase before output.

**Comment by coltoneshaw** [comment]
![Screenshot 2024-03-12 at 1 55 58 PM](https://github.com/coltoneshaw/mmhealth/assets/46071821/7c2adf4a-344e-4ce3-bb3f-e696f91518b1)

Fixed
